//Implementing Flucoma Analysis Tools into Sway

FluidSpectralShape
FluidOnsetFeature
FluidAmpFeature
FluidAmpGate

~in = NodeProxy.audio(s, 1);
~in.source = {SoundIn.ar(0)};


~analysis = NodeProxy.control(s, 7);
FluidSpectralShape

//Processing Idea

//Concat2
//How can I access audio from other instances of Sway currently running?

processing.source = {};

//Corpus Creation and Live corpus manipulation

SwayConstructor

//Variable phrase lengths for time limit?


//testing speaker amplitude, what is expected amplitude deviation

101.sqrt

1/100.ampdb

0.025.dbamp

//-40db expected amplitude differential for my speakers

//3db change fix it

//try pink noise or an fm tone
//roll off the noise at 2k



